// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// AuthAPI is an autogenerated mock type for the AuthAPI type
type AuthAPI struct {
	mock.Mock
}

// Login provides a mock function with given fields: c
func (_m *AuthAPI) Login(c *gin.Context) {
	_m.Called(c)
}

// Logout provides a mock function with given fields: c
func (_m *AuthAPI) Logout(c *gin.Context) {
	_m.Called(c)
}

// Refresh provides a mock function with given fields: c
func (_m *AuthAPI) Refresh(c *gin.Context) {
	_m.Called(c)
}
