// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ProductAPI is an autogenerated mock type for the ProductAPI type
type ProductAPI struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: c
func (_m *ProductAPI) AddProduct(c *gin.Context) {
	_m.Called(c)
}

// DeleteProduct provides a mock function with given fields: c
func (_m *ProductAPI) DeleteProduct(c *gin.Context) {
	_m.Called(c)
}

// GetAllProducts provides a mock function with given fields: c
func (_m *ProductAPI) GetAllProducts(c *gin.Context) {
	_m.Called(c)
}

// GetProductByID provides a mock function with given fields: c
func (_m *ProductAPI) GetProductByID(c *gin.Context) {
	_m.Called(c)
}

// UpdateProduct provides a mock function with given fields: c
func (_m *ProductAPI) UpdateProduct(c *gin.Context) {
	_m.Called(c)
}
