// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// UserAPI is an autogenerated mock type for the UserAPI type
type UserAPI struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: c
func (_m *UserAPI) AddUser(c *gin.Context) {
	_m.Called(c)
}

// DeleteUser provides a mock function with given fields: c
func (_m *UserAPI) DeleteUser(c *gin.Context) {
	_m.Called(c)
}

// GetAllUsers provides a mock function with given fields: c
func (_m *UserAPI) GetAllUsers(c *gin.Context) {
	_m.Called(c)
}

// GetUserByID provides a mock function with given fields: c
func (_m *UserAPI) GetUserByID(c *gin.Context) {
	_m.Called(c)
}

// UpdateUser provides a mock function with given fields: c
func (_m *UserAPI) UpdateUser(c *gin.Context) {
	_m.Called(c)
}
